name: Terraform Apply
on:
  push:
    branches:
      - main
permissions:
  contents: read
  id-token: write
jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::864981717146:role/GitHubActionsTerraformRole
          aws-region: us-east-1
          audience: sts.amazonaws.com
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0
      - name: Terraform Init
        run: terraform init
      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          TF_LOG: DEBUG